import "../styles/globals.css";
import HEAD from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <HEAD>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&display=swap"
          rel="stylesheet"
        ></link>
      </HEAD>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
